Update Jenkinsfile

diff --git a/registration-app/Jenkinsfile b/registration-app/Jenkinsfile
--- a/registration-app/Jenkinsfile
+++ b/registration-app/Jenkinsfile
@@ -3,7 +3,7 @@ pipeline {
 
     environment {
         DOCKER_CONFIG = '/home/ec2-user/.docker'
-        PATH = "/usr/bin:/usr/local/bin:/usr/libexec/docker/cli-plugins:$PATH"
+        PATH = "/usr/local/bin:/usr/bin:/bin:/usr/libexec/docker/cli-plugins:$PATH"
     }
 
     stages {
@@ -34,8 +34,7 @@ pipeline {
             steps {
                 dir('registration-app') {
                     sh '''
-                    /usr/bin/docker compose version
-                    /usr/bin/docker compose down || true
+                    docker compose down || true
                     '''
                 }
             }
@@ -43,9 +42,7 @@ pipeline {
 
         stage('Pull Latest Image') {
             steps {
-                sh '''
-                docker pull balachandru1/registration-app:latest
-                '''
+                sh 'docker pull balachandru1/registration-app:latest'
             }
         }
 
@@ -53,8 +50,7 @@ pipeline {
             steps {
                 dir('registration-app') {
                     sh '''
-                    /usr/bin/docker compose version
-                    /usr/bin/docker compose up -d
+                    docker compose up -d
                     '''
                 }
             }
@@ -62,19 +58,17 @@ pipeline {
 
         stage('Verify Running Containers') {
             steps {
-                sh '''
-                docker ps
-                '''
+                sh 'docker ps'
             }
         }
     }
 
     post {
         success {
-            echo '✅ Deployment completed successfully and pipeline is successfully created'
+            echo '✅ Deployment completed successfully'
         }
         failure {
-            echo '❌ Deployment failed and got error'
+            echo '❌ Deployment failed'
         }
     }
 }
